apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: hb-namespace
spec:
  selector:
    matchLabels:
      app: helloworld-pod
  template:
    metadata:
      labels:
        app: helloworld-pod
    spec:
      containers:
      - name: helloworld-container
        image: helloworld:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
