
apiVersion: v1
kind: Namespace
metadata:
  name: hb-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: hb-namespace
spec:
  selector:
    matchLabels:
      app: helloworld-pod
  template:
    metadata:
      labels:
        app: helloworld-pod
    spec:
      containers:
      - name: helloworld-container
        image: 505178285116.dkr.ecr.us-east-1.amazonaws.com/helloworld:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: hb-namespace
spec:
  selector:
    app: helloworld-pod
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

